/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fcxezpunhdyxrizphncv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjeGV6cHVuaGR5eHJpenBobmN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0NzM2MDQsImV4cCI6MjA4MzA0OTYwNH0.jpQIRYah4UpV8Cpr2N-8s3-mr1mSUYBSg_8tsYLsXM0"